/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Surfer' at '29/03/17 10:09 PM' with Gradle 2.14.1
 *
 * @author Surfer, @date 29/03/17 10:09 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
